update CI (3): remove unused drone config, fixes for github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,6 +85,7 @@ jobs:
           GCOVTOOL: ${{ matrix.gcovtool }}
           TRAVIS_BRANCH: ${{ github.base_ref }}
           TRAVIS_OS_NAME: "linux"
+          
         run: |
           echo '==================================> SETUP'
           BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
@@ -209,8 +210,13 @@ jobs:
           OTHER_LIBS=`grep "submodule .*" .gitmodules | sed 's/\[submodule\ "\(.*\)"\]/"\*\/boost\/\1\.hpp" "\*\/boost\/\1\/\*"/g'| sed "/\"\*\/boost\/$BOOST_LIBS_FOLDER\/\*\"/d" | sed ':a;N;$!ba;s/\n/ /g'`
           echo $OTHER_LIBS
           eval "$LCOV --remove $TRAVIS_BUILD_DIR/coverals/coverage.info $OTHER_LIBS -o $TRAVIS_BUILD_DIR/coverals/coverage.info"
-          cd $TRAVIS_BUILD_DIR
-          sudo gem install coveralls-lcov || echo "ERROR. Failed to install coveralls-lcov"
-          coveralls-lcov coverals/coverage.info
+          #cd $TRAVIS_BUILD_DIR
+          #sudo gem install coveralls-lcov || echo "ERROR. Failed to install coveralls-lcov"
+          #coveralls-lcov --repo-token "${SECRETS_GITHUB_TOKEN}" coverals/coverage.info
 
           fi
+      - name: Coveralls
+        uses: coverallsapp/github-action@master
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          path-to-lcov: $TRAVIS_BUILD_DIR/coverals/coverage.info
